before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: UXPdMhvd3h9sQO1n+KL0JFCztGDOugjzROE8/f9+BafAXicGw8Let3uKS1OfqrrfkiYNaC46alYUM2OdyXGyOEt7wvQ2A2znNRLGXA2xvyi7QWgqVOjDYP3085o/j+3Uberg9BaYuRgNdOJDHGUcKAAq00bQVXvCOplbBTZH9YOn+esTRFA+JeQQXg8olEf6FHe8L+/Ik/rcd8pAVxp/khRoH4rqVml5X/ld1mbFTgwQfJSgKMuPXQ7PLpenbt5ASDwW6aM8NwQdF9GsKW8MvNelr+z2LUKj2fOcec3eDflWNjXMk4KuC0FbdzG3/jnQsA4BHX4seMTl/EOObdOHYFyOzpARvDPQp5xT50xCR4C+3olDtSSeQVp7N9vzFOAEminCZqN/n/nSaK3v9GGhEB6a+Oi1Tz9gkR3BPuu0SeQnyFRM2FGfwu04yS9W/V+EN7sM5BfTZl+/XFZqyPFbMODX8sT7PBxYcb+MRrX3fcUBut6TFsdcZbdGdItt/m5XEbZti/DDadJUIbRRyi+G+lktnN0j6Y073PMqSoZ3nLkNYaERMbJVpGMcRRfUHRl05VAGKXvROb8BX2TJ36URM6a4jiBi8bmeny1Z1JvMu7sFjbCYFthfPTCU92uznJSnf0bWExBakqfS4ZA7I4RpWwmtt11MWFeuQv2dGJgyHW4= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
